theme: jekyll-theme-slate
title: "EcoCast AI: Melter Optimizer & Digital Twin"
description: "Schneider Electric Yuva Yodha Hackathon 2026 - AI Decision Support & Melter Optimization Platform"
show_downloads: false
google_analytics: null
